dist: trusty

language: node_js

node_js:
  - "6.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: true

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install webpack typings http-server tslint protractor -g

install:
  - npm install

before_script:
 - chmod +x ./config/test.sh

script:
  - npm run build
  - npm run test
  - ./config/test.sh
